spring:
  application:
    name: photo-service
  r2dbc:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  flyway:
    url: ${FLYWAY_URL}
    baseline-on-migrate: true
    enabled: true
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ${NCP_ACCESS_KEY}
      secret-key: ${NCP_SECRET_KEY}
    stack:
      auto: false
    region:
      static: kr-standard
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: ${NCP_BUCKET}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin/api/v2/spans
