spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000,https://mafoo.kr,https://dev.mafoo.kr,https://gateway.mafoo.kr'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
      routes:
        - id: user-service
          uri: https://user-service.mafoo.kr
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>/?.*), /$\{segment}
        - id: photo-service
          uri: https://photo-service.mafoo.kr
          predicates:
            - Path=/photo/**
          filters:
            - RewritePath=/photo/(?<segment>/?.*), /$\{segment}
springdoc:
  swagger-ui:
    urls[0]:
      name: "유저 서비스"
      url: https://gateway.mafoo.kr/user/v3/api-docs

    urls[1]:
      name: "사진 서비스"
      url: https://gateway.mafoo.kr/photo/v3/api-docs
