spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000,https://mafoo.kr,https://dev.mafoo.kr,https://gateway.mafoo.kr'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
      routes:
        - id: user-service-swagger
          uri: http://user-service
          predicates:
              - Path=/user/v3/api-docs/**
          filters:
              - RewritePath=/user/(?<segment>/?.*), /$\{segment}
        - id: user-service-auth
          uri: http://user-service
          predicates:
            - Path=/user/v1/auth/**
          filters:
            - RewritePath=/user/(?<segment>/?.*), /$\{segment}
        - id: photo-service-swagger
          uri: http://photo-service
          predicates:
            - Path=/photo/v3/api-docs/**
          filters:
            - RewritePath=/photo/(?<segment>/?.*), /$\{segment}
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/user/**
          filters:
            - JWTAuthenticationFilter
            - RewritePath=/user/(?<segment>/?.*), /$\{segment}
        - id: photo-service
          uri: http://photo-service
          predicates:
            - Path=/photo/**
          filters:
            - JWTAuthenticationFilter
            - RewritePath=/photo/(?<segment>/?.*), /$\{segment}
springdoc:
  swagger-ui:
    urls[0]:
      name: "유저 서비스"
      url: https://gateway.mafoo.kr/user/v3/api-docs

    urls[1]:
      name: "사진 서비스"
      url: https://gateway.mafoo.kr/photo/v3/api-docs

app:
  jwt:
    verify-key: ${JWT_VERIFY_KEY}
