spring:
  application:
    name: admin-service

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

app:
  url:
    photo-service: http://photo-service
    user-service: http://user-service
